var data = 
{
    "userCode": "",
    "channel": "",
    "transTime": "",
    "transToken": "",
    "statusCode": "000000",
    "statusMessage": "",
    "returns": {
        "calculationInfos": [
            {
                "calCode": "age",
                "calName": "承保年龄",
                "calOrder": 1,
                "defaultValue": null,
                "showType": "label",
                "ifRequired": "1",
                "calDetails": [
                    {
                        "enuCode": "18-60",
                        "enuContent": "18-60周岁"
                    }
                ]
            },
            {
                "calCode": "pay_period",
                "calName": "缴费期间",
                "calOrder": 1,
                "defaultValue": null,
                "showType": "listArea",
                "ifRequired": "1",
                "calDetails": [
                    {
                        "enuCode": "0",
                        "enuContent": "趸交"
                    },
                    {
                        "enuCode": "3",
                        "enuContent": "3年"
                    },
                    {
                        "enuCode": "5",
                        "enuContent": "5年"
                    },
                    {
                        "enuCode": "10",
                        "enuContent": "10年"
                    },
                    {
                        "enuCode": "15",
                        "enuContent": "15年"
                    },
                    {
                        "enuCode": "20",
                        "enuContent": "20年"
                    }
                ]
            },
            {
                "calCode": "guarantee_term",
                "calName": "保障期限",
                "calOrder": 1,
                "defaultValue": null,
                "showType": "label",
                "ifRequired": "1",
                "calDetails": [
                    {
                        "enuCode": "30年、至80周岁",
                        "enuContent": "30年、至80周岁"
                    }
                ]
            }
        ],
        "commodityCombination": {
            "id": 105,
            "commodityCombinationCode": "00100002",
            "commodityCombinationName": "泰康乐行综合意外保障计划",
            "commodityCombinationType": "02",
            "companyId": 1,
            "startPiece": "",
            "insuredAge": "18-60周岁",
            "insuredDuration": "30年、至80周岁",
            "insuredInfo": "两全险优势，满期可返还|住院享津贴，意外有保障",
            "paymentDeadline": "趸交、3年交、5年交、10年交、15年交、20年交",
            "commodityCombinationImage": null,
            "banner": "babyCancer.png",
            "isCommission": "0",
            "commissionShowType": "02",
            "commodityId": null,
            "commodityCombinationStatus": "1",
            "commodityCombinationRate": "",
            "commodityCombinationOrder": null,
            "dateCreated": null,
            "createdBy": "",
            "dateUpdated": null,
            "updatedBy": "",
            "remark": ""
        },
        "commodityInfoList": [
            {
                "id": 118,
                "commodityCode": null,
                "commodityName": null,
                "commodityType": null,
                "companyId": null,
                "riskType": null,
                "banner": "",
                "insuredAge": null,
                "insuredInfo": null,
                "insuredDuration": null,
                "paymentDeadline": null,
                "dateCreated": null,
                "createdBy": null,
                "dateUpdated": null,
                "updatedBy": null,
                "remark": ""
            },
            {
                "id": 119,
                "commodityCode": null,
                "commodityName": null,
                "commodityType": null,
                "companyId": null,
                "riskType": null,
                "banner": "",
                "insuredAge": null,
                "insuredInfo": null,
                "insuredDuration": null,
                "paymentDeadline": null,
                "dateCreated": null,
                "createdBy": null,
                "dateUpdated": null,
                "updatedBy": null,
                "remark": ""
            },
            {
                "id": 120,
                "commodityCode": null,
                "commodityName": null,
                "commodityType": null,
                "companyId": null,
                "riskType": null,
                "banner": "",
                "insuredAge": null,
                "insuredInfo": null,
                "insuredDuration": null,
                "paymentDeadline": null,
                "dateCreated": null,
                "createdBy": null,
                "dateUpdated": null,
                "updatedBy": null,
                "remark": ""
            },
            {
                "id": 121,
                "commodityCode": null,
                "commodityName": null,
                "commodityType": null,
                "companyId": null,
                "riskType": null,
                "banner": "",
                "insuredAge": null,
                "insuredInfo": null,
                "insuredDuration": null,
                "paymentDeadline": null,
                "dateCreated": null,
                "createdBy": null,
                "dateUpdated": null,
                "updatedBy": null,
                "remark": ""
            },
            {
                "id": 122,
                "commodityCode": null,
                "commodityName": null,
                "commodityType": null,
                "companyId": null,
                "riskType": null,
                "banner": "",
                "insuredAge": null,
                "insuredInfo": null,
                "insuredDuration": null,
                "paymentDeadline": null,
                "dateCreated": null,
                "createdBy": null,
                "dateUpdated": null,
                "updatedBy": null,
                "remark": ""
            },
            {
                "id": 123,
                "commodityCode": null,
                "commodityName": null,
                "commodityType": null,
                "companyId": null,
                "riskType": null,
                "banner": "",
                "insuredAge": null,
                "insuredInfo": null,
                "insuredDuration": null,
                "paymentDeadline": null,
                "dateCreated": null,
                "createdBy": null,
                "dateUpdated": null,
                "updatedBy": null,
                "remark": ""
            }
        ],
        "companyInfo": {
            "id": 1,
            "companyCode": "00001",
            "companyName": "泰康人寿",
            "companyInsurance": null,
            "companyType": null,
            "companyProfile": "taikangIntro.html",
            "comIcon": "taikang.png",
            "honor": null,
            "insurancePolicy": "taikangRule.html",
            "companyStatus": "1",
            "dateCreated": null,
            "createdBy": null,
            "dateUpdated": null,
            "updatedBy": null,
            "remark": null
        },
        "commodityModuleList": [
            {
                "id": 49,
                "commodityCombinationId": 105,
                "moduleType": "01",
                "bigModuleName": "产品介绍",
                "moduleName": "产品特色",
                "subModuleName": "",
                "modueInfo": "意外保障真全面|无论如何都返还|住院津贴额外赔|乐行天下永无忧",
                "moduleOrder": 1,
                "dateCreated": null,
                "createdBy": "",
                "dateUpdated": null,
                "updatedBy": "",
                "remark": ""
            }
        ],
        "commodityClauseList": [
            {
                "commodityId": 118,
                "productId": 114,
                "riskClass": "01",
                "isNeed": "1",
                "cpLinkRemark": "",
                "productCode": "00100004",
                "productName": "泰康乐行两全保险",
                "productType": "",
                "productClass": "两全保险",
                "companyId": 1,
                "insurancClause": "泰康乐行两全保险条款",
                "insuranceRecordNumber": "[2015]309号1",
                "insuredAge": "",
                "paymentDeadline": "",
                "insuredDuration": "",
                "insurancClauseDownload": "http://www.baidu.com",
                "productStatus": "1",
                "remark": ""
            },
            {
                "commodityId": 118,
                "productId": 115,
                "riskClass": "02",
                "isNeed": "0",
                "cpLinkRemark": "",
                "productCode": "00100005",
                "productName": "泰康附加乐行意外保障定期寿险",
                "productType": "",
                "productClass": "定期寿险",
                "companyId": 1,
                "insurancClause": "泰康附加乐行意外保障定期寿险条款",
                "insuranceRecordNumber": "[2015]309号2",
                "insuredAge": "",
                "paymentDeadline": "",
                "insuredDuration": "",
                "insurancClauseDownload": "http://www.baidu.com",
                "productStatus": "1",
                "remark": ""
            },
            {
                "commodityId": 118,
                "productId": 116,
                "riskClass": "02",
                "isNeed": "0",
                "cpLinkRemark": "",
                "productCode": "00100006",
                "productName": "泰康附加乐行意外住院津贴医疗保险",
                "productType": "",
                "productClass": "医疗险",
                "companyId": 1,
                "insurancClause": "泰康附加乐行意外住院津贴医疗保险条款",
                "insuranceRecordNumber": "[2015]309号3",
                "insuredAge": "",
                "paymentDeadline": "",
                "insuredDuration": "",
                "insurancClauseDownload": "http://www.baidu.com",
                "productStatus": "1",
                "remark": ""
            }
        ]
    }
}


var data1 = {
	"userCode": "13651746000",
	"channel": "01",
	"transTime": "2017-08-25 10:58:42",
	"transToken": "",
	"statusCode": "000000",
	"statusMessage": "",
	"returns": {
		"CommodityInfo": [{
			"id": 1,
			"commodityCode": null,
			"commodityName": null,
			"commodityType": null,
			"companyId": null,
			"riskType": null,
			"banner": "https://td-pro.ta-by.com/tongdaoPlatform/tongdaoApp/page/image/cancerRisk/man1.png",
			"insuredAge": null,
			"insuredInfo": null,
			"insuredDuration": null,
			"paymentDeadline": null,
			"dateCreated": null,
			"createdBy": null,
			"dateUpdated": null,
			"updatedBy": null,
			"remark": ""
		},
		{
			"id": 2,
			"commodityCode": null,
			"commodityName": null,
			"commodityType": null,
			"companyId": null,
			"riskType": null,
			"banner": "https://td-pro.ta-by.com/tongdaoPlatform/tongdaoApp/page/image/cancerRisk/man1.png",
			"insuredAge": null,
			"insuredInfo": null,
			"insuredDuration": null,
			"paymentDeadline": null,
			"dateCreated": null,
			"createdBy": null,
			"dateUpdated": null,
			"updatedBy": null,
			"remark": ""
		}],
		"commodityCombinationModuleMapper": [{
			"id": 1,
			"commodityCombinationId": 1,
			"moduleType": "01",
			"bigModuleName": "产品介绍",
			"moduleName": "图片介绍",
			"subModuleName": "",
			"modueInfo": "https://td-pro.ta-by.com/tongdaoPlatform/tongdaoApp/page/image/cancerRisk/manproduct.png",
			"moduleOrder": 1,
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		},
		{
			"id": 2,
			"commodityCombinationId": 1,
			"moduleType": "02",
			"bigModuleName": "产品介绍",
			"moduleName": "常见问题",
			"subModuleName": "",
			"modueInfo": "\u003cul class\u003d\"wenda \"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 什么是等待期？本产品等待期多长？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 等待期又称观察期，是指需要对保险人的健康情况观察一段时间，在这段时间里如果发生保险事故将不会获得赔偿。本产品的等待期为180天，连续续保时不会再设等待期。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda \"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 申请理赔需要提供哪些材料？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 本产品确诊即赔，需要有能证明是在保险保障期间患病的证明，比如二级或二级合格以上的医院，且具有资质的专科医生的恶性肿瘤诊断书、病理检查相关报告等，经天安确认无误后即可按保险金额进行赔付。\u003c/li\u003e\n         \u003c/ul\u003e         \n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 本产品受益人可以指定吗？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 本产品受益人法定不可指定。本产品的保险金的受益人是被保险人本人；如被保险人身故的，受益人只能是法定受益人，按照遗产继承规则处理，也就是依照《中华人民共和国继承法》规定进行处理。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 如何报案？如何申请理赔金？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 报案情拨打天安财产保险公司24小时客服热线95505转1报案理赔专线。理赔金在所在地天安分公司直接申请即可\u003c/li\u003e\n         \u003c/ul\u003e         \n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 本保险为电子保单，网上出具电子保单是否具有法律效率？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 本产品为您提供的是电子保单，根据《中华人民共和国合同法》第十一条规定，数据电文是合法的合同表现形式，电子保单与纸质保单具有同等法律效力。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 可购买区域是指什么？是否全国通赔？如果购买后去了不属于购买区域的地区出险了是否可以理赔？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 可购买的区域指的是页面上列明的可购买本产品的区域，只有投保人、被保险人的长期居住地属于本产品的可购买区域才能够购买本产品，长期居住地一般是指工作地。本公司在港澳台、青海，宁夏，内蒙古，西藏自治区除外均设有分公司，本产品全国通赔，支持异地理赔。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 外籍人士能买么？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 本产品被保险人只限制中国国籍的大陆人士（港、澳、台除外）。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 哪些情况不保？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 对于下列是不能承保的项目，也是不承担保险责任的项目，一旦发生理赔，会有拒赔风险\u003cbr /\u003e\n           一、条款中列明的除外责任不能承保如：\u003cbr /\u003e\n               （1）原位癌；\u003cbr /\u003e\n           　（2）相当于Binet分期方案A期程度的慢性淋巴细胞白血病；\u003cbr /\u003e\n           　（3）相当于AnnArbor分期方案I期程度的何杰金氏病；\u003cbr /\u003e\n           　（4）皮肤癌（不包括恶性黑色素瘤及已发生转移的皮肤癌）；\u003cbr /\u003e\n           　（5）TNM分期为T1N0M0期或者更轻分期的前列腺癌；\u003cbr /\u003e\n           　（6）感染艾滋病病毒或者患艾滋病期间所患恶性肿瘤。\u003cbr /\u003e\n           　（7）转移恶性肿瘤（即恶性肿瘤细胞从原发部位侵入血管、淋巴管或体腔，并在其他部位或器官继续生长， 形成与原发部位恶性肿瘤相同类型的恶性肿瘤）。\u003cbr /\u003e\n           二、投保时，健康告知问卷中任意一项答复为“是”的；\u003cbr /\u003e\n           三、其他情况详见条款及投保告知信息\u003cbr /\u003e\n          \u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 你们这款保险需要到医院体检吗？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 您好！该保障计划投保时是不需要到医院体检，但是需要如实告知，仔细填写健康问卷，满足健康问卷要求方可投保。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 被保险人没有办理身份证，改如何投保？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 如果被保险人还没有办理身份证，如有户口本可查户口本上的身份证号码，填写身份证号即可。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 请问以前生过被保范围内的肿瘤疾病，现在已经医好了，能买这款保险吗？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 非常抱歉，之前患有恶性肿瘤的，不能购买本产品。购买前需确认健康告知，如曾经出现健康告知中的病症，是不能购买的。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 在别的保险公司买过防癌险，还能买这个防癌疾病保险吗？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 在其他保险公司买过重大防癌险，仍然可以购买本产品。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 这款防癌疾病保险购买后有犹豫期吗？如何退保？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 本产品无犹豫期。投保后无法撤销，退保会造成损失，请慎重退保。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 如果已经有社保，那还有必要买该险种吗？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 与社保报销医疗费的方式不同，本产品是一个专门癌症的保障，属于疾病类保险，而非住院类保险，一旦确诊，按保险金额进行赔付，减轻您的经济压力，同时我们还提供海外医疗服务，提供患病后的治愈成功率。\u003c/li\u003e\n         \u003c/ul\u003e         \n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 保额理赔是一年内累计，还是只能用一次？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 保额赔付只能用一次，癌症确诊即赔，即按保额进行赔付。\u003c/li\u003e\n         \u003c/ul\u003e         \n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 怎么理解未满期净保费 ？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 简单点说未满期净保费是指您在保险期间内退保时能够拿到的退保费用。具体是指被保险人或投保人在保险还未到期前向天安申请退保，对其剩余未到期需要退给被保险人或投保人的费用金额为未满期净保费；其计算公式\u003d保险费×[1-(保险单已经过天数/保险期间天数)] ×（1-30%）。经过天数不足一天的按一天计算。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 天安恶性肿瘤疾病保险是不是所有肿瘤都包括？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 我司恶性肿瘤疾病保险已包含绝大多数的恶性肿瘤，但只有极少部分的恶性肿瘤比如在患艾滋病期间感染的恶性肿瘤等情况是包含的，具体可以参考我们的条款。\u003c/li\u003e\n         \u003c/ul\u003e                  \n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 什么是高发性恶性肿瘤？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 高发性恶性肿瘤是针对发病率比较高的癌症（最高发布率可以占癌症险发病率的70%以上）而设计的保险保障，主要特点是保费低、保额高，能提供主要保障。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 男性高发类的癌症具体针对哪些癌症进行保障？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 指原发于气管、支气管和肺、胃、肝、直肠、结肠、食管的恶性肿瘤，如果需要保障更全的，可以推荐你购买我司的恶性肿瘤疾病保险产品。\u003c/li\u003e\n         \u003c/ul\u003e\n         \u003cul class\u003d\"wenda none\"\u003e\n          \u003cli\u003e\u003cb class\u003d\"wen\"\u003e\u003c/b\u003e 女性高发类的癌症具体针对哪些癌症进行保障？\u003c/li\u003e\n          \u003cli class\u003d\"li1\"\u003e\u003cb class\u003d\"da\"\u003e\u003c/b\u003e 女性高发恶性肿瘤是指原发于女性乳房、气管、支气管和肺、子宫颈、胃、甲状腺的恶性肿瘤，如果需要保障更全的，可以推荐你购买我司的恶性肿瘤疾病保险产品。\u003c/li\u003e\n         \u003c/ul\u003e",
			"moduleOrder": 2,
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		},
		{
			"id": 3,
			"commodityCombinationId": 1,
			"moduleType": "03",
			"bigModuleName": "详细说明",
			"moduleName": "合同条款及样张",
			"subModuleName": "合同样张",
			"modueInfo": "https://td-pro.ta-by.com/tongdaoPlatform/tongdaoApp/page/image/cancerRisk/nanpolicy.jpg",
			"moduleOrder": 1,
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		},
		{
			"id": 4,
			"commodityCombinationId": 1,
			"moduleType": "02",
			"bigModuleName": "详细说明",
			"moduleName": "保险须知",
			"subModuleName": "",
			"modueInfo": "\u003cbr /\u003e 1、本产品为一年期健康保险，确诊即赔。\n          \u003cbr /\u003e 2、180天等待期后，被保险人经医院初次确证罹患恶性肿瘤，天安财险按保险金额给付保险金。\n          \u003cbr /\u003e 3、承保年龄：18-59周岁\n          \u003cbr /\u003e 4、保单形式：电子保单\n          \u003cbr /\u003e 5、保单生效时间：投保后次日零时\n          \u003cbr /\u003e 6、恶性肿瘤或高发恶性肿瘤单项投保最高赔付100万，双项投保最高赔付100万。\n          \u003cbr /\u003e 7、本保险适用条款为《天安恶性肿瘤疾病保险条款》、《天安男性高发恶性肿瘤疾病保险条款》。\n          \u003cbr /\u003e 8、投保人和被保险人关系需为以下其一：（1）本人（2）父母（3）子女（4）配偶。\n          \u003cbr /\u003e 9、被保险人仅限男性。\n          \u003cbr /\u003e 10、男性高发恶性肿瘤是指原发于男性气管、支气管和肺、胃、肝、直肠、结肠、食管的恶性肿瘤。\n          \u003cbr /\u003e\n          \u003cbr /\u003e\n          \u003cdiv class\u003d\"none baodan_block\"\u003e\n           海外远程会诊及转诊服务介绍\u003cbr /\u003e 凡购买天安“恶性肿瘤保险”产品的客户并符合相关条件，均可获得一次海外医疗专家视频会诊和海外就医转诊直通车服务。\n           \u003cbr /\u003e\n           \u003cbr /\u003e 1、远程会诊\n           \u003cbr /\u003e 诊疗初步方案及建议\n           \u003cbr /\u003e 病历翻译\n           \u003cbr /\u003e 国外医院推荐\n           \u003cbr /\u003e 专家预约\n           \u003cbr /\u003e 远程会诊方案\n           \u003cbr /\u003e 远程会诊结果翻译\n           \u003cbr /\u003e 注：远程会诊服务对象为保额大于等于50万一年的被保险人\n           \u003cbr /\u003e\n           \u003cbr /\u003e 2、国外医疗首诊服务\n           \u003cbr /\u003e 国外诊疗方案制定\n           \u003cbr /\u003e 海外医院预约\n           \u003cbr /\u003e 签证办理\n           \u003cbr /\u003e 国外治疗安排\n           \u003cbr /\u003e 国外首诊服务\n           \u003cbr /\u003e 注：国外医疗首诊服务对象为保额大于等于100万一年的被保险人\n           \u003cbr /\u003e\n           \u003cbr /\u003e 更多详细服务内容，可咨询天安佰盈客服热线400-689-5505\n           \u003cbr /\u003e\n          \u003c/div\u003e\n          \u003cdiv class\u003d\"chakangduo click_img\" data-click\u003d\"baodan_block\"\u003e\n           \u003cspan class\u003d\"s1\"\u003e查看更多\u003c/span\u003e \u003cspan class\u003d\"iconfont\"\u003e\u003c/span\u003e\n          \u003c/div\u003e",
			"moduleOrder": 2,
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		},
		{
			"id": 5,
			"commodityCombinationId": 1,
			"moduleType": "02",
			"bigModuleName": "详细说明",
			"moduleName": "理赔保障",
			"subModuleName": "",
			"modueInfo": "本保险产品由天安财产保险股份有限公司承保，您可通过天安财险官方热线95505提出理赔申请，或联系您的专属同道代理人，为您提供全程协助理赔服务，让您理赔更快捷、更省心、更放心。",
			"moduleOrder": 3,
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		},
		{
			"id": 6,
			"commodityCombinationId": 1,
			"moduleType": "01",
			"bigModuleName": "详细说明",
			"moduleName": "理赔指引",
			"subModuleName": "",
			"modueInfo": "https://td-pro.ta-by.com/tongdaoPlatform/tongdaoApp/page/image/cancerRisk/lipei.jpg",
			"moduleOrder": 4,
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		},
		{
			"id": 7,
			"commodityCombinationId": 1,
			"moduleType": "02",
			"bigModuleName": "详细说明",
			"moduleName": "保单查询",
			"subModuleName": "",
			"modueInfo": "\u003cp\u003e\n          1.本合同采用电子保险单形式承保，您可以登录天安财产保险官网查询保单。\n         \u003c/p\u003e\n         \u003cp\u003e\n          2.本产品由天安财产保险股份有限公司承保，客户购买该产品，如有理赔、保全、退保等需求，可拨打\u003ca style\u003d\"white-space:normal;\" class\u003d\"rexian\"\u003e95505\u003c/a\u003e转1进行办理，理赔款、退保产生的未满期净保费等通过银行进行转账付款，具体付款方式或账号由申请人决定。\n         \u003c/p\u003e",
			"moduleOrder": 5,
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		},
		{
			"id": 8,
			"commodityCombinationId": 1,
			"moduleType": "02",
			"bigModuleName": "详细说明",
			"moduleName": "续保、退保及发票",
			"subModuleName": "",
			"modueInfo": "续保：首次投保保单时间到期前，将会通过短信发送投保链接给投保人，只要在期满前点击投保链接，完成付款即可完成续保。续保无等待期也不需要重新进行健康告知。\u003cbr /\u003e \n         退保：本保险不提供在线退保，下单后如需退保，可以联系天安财险客服热线95505提交退保申请，按要求提交相关材料后即可退保。\n         \u003cbr /\u003e 发票：下单后如需发票，可以联系天安财险客服热线95505进行处理。\n         \u003cbr /\u003e",
			"moduleOrder": 6,
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		}],
		"commodityCombination": {
			"id": 1,
			"commodityCombinationCode": "00400001",
			"commodityCombinationName": "天安防癌险（男神版）",
			"commodityCombinationType": "01",
			"companyId": 4,
			"startPiece": "15元/起",
			"insuredAge": "18-59岁",
			"insuredDuration": "一年",
			"insuredInfo": "支付100万",
			"paymentDeadline": null,
			"commodityCombinationImage": null,
			"banner": "https://td-pro.ta-by.com/tongdaoPlatform/tongdaoApp/page/image/cancerRisk/man1.png",
			"isCommission": "1",
			"commissionShowType": "01",
			"commodityId": 1,
			"commodityCombinationStatus": "1",
			"commodityCombinationRate": "25",
			"commodityCombinationOrder": 1,
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		},
		"mainList": [{
			"id": 1,
			"productCode": "00400001",
			"productName": "恶性肿瘤疾病",
			"productType": "财产保险",
			"productClass": "疾病保险",
			"companyId": 4,
			"insurancClause": "恶性肿瘤疾病保险条款",
			"insuranceRecordNumber": "（天安财险）（备-疾病保险）【2016】（主）046号",
			"insuredAge": "出生30天-59岁",
			"paymentDeadline": "趸交",
			"insuredDuration": "1年",
			"insurancClauseDownload": "http://www.baidu.com",
			"productStatus": "1",
			"companyRiskCode": "1016",
			"companyPlanCode": "41111",
			"dateCreated": null,
			"createdBy": "",
			"dateUpdated": null,
			"updatedBy": "",
			"remark": ""
		}],
		"healthTold": [],
		"addList": []
	}
}

var data3 = {"userCode":"13800000000","channel":"01","transTime":"2017-08-26 14:15:05","transToken":"","statusCode":"000000","statusMessage":"","returns":{"customerBasic":{"id":8,"userName":"15978132785","password":"8c8d88c9b526683bdbf897ae809d90e4","userAppImage":null,"userImage":null,"name":"苏健敏","idType":"01","idNo":"450403198108311523","provinceCode":"250000","provinceName":"广西","cityCode":"250001","cityName":"南宁","detailAddress":null,"sex":"2","birthday":null,"mobile":"15978132785","email":null,"idAuth":"1","authTime":"2017-08-23 17:07:48","authResource":null,"commissionSwitch":"1","type":"04","inviterId":null,"customerSourceComment":"1","status":"1","leaveDate":null,"leaveRole":null,"riskSupportAbility":null,"isFirst":"1","channelSource":"01","isFirstAuth":"0","lastLoginTime":"2017-08-23 17:07:48","dateCreated":"2017-08-23 09:52:47","createdBy":"system","dateUpdated":"2017-08-23 17:07:48","updatedBy":"system_realName","remark":null}}}
var data4 = {
    "userCode": "",
    "channel": "",
    "transTime": "",
    "transToken": "",
    "statusCode": "000000",
    "statusMessage": "",
    "returns": {
        "calOptionDtos": [
            {
                "id": 1,
                "commodityCombinationId": 1,
                "calName": "保障方案",
                "calCode": "versions",
                "enuCode": "01",
                "enuContent": "基础版",
                "commodityFlag": "1",
                "commodityId": null,
                "calOrder": 1,
                "isCal": "1",
                "isDefalut": null,
                "showType": "listArea",
                "isRequired": null,
                "calOptions": [
                    {
                        "id": 1,
                        "commodityCombinationId": 1,
                        "calName": "保障方案",
                        "calCode": "versions",
                        "enuCode": "01",
                        "enuContent": "基础版",
                        "commodityFlag": "1",
                        "commodityId": 1,
                        "calOrder": 1,
                        "isCal": "1",
                        "isDefalut": "1",
                        "showType": "listArea",
                        "isRequired": "1",
                        "createdBy": null,
                        "dateCreated": null,
                        "updatedBy": null,
                        "dateUpdated": null,
                        "remark": null
                    },
                    {
                        "id": 2,
                        "commodityCombinationId": 1,
                        "calName": "保障方案",
                        "calCode": "versions",
                        "enuCode": "02",
                        "enuContent": "高级版",
                        "commodityFlag": "1",
                        "commodityId": 2,
                        "calOrder": 1,
                        "isCal": "1",
                        "isDefalut": "0",
                        "showType": "listArea",
                        "isRequired": "1",
                        "createdBy": null,
                        "dateCreated": null,
                        "updatedBy": null,
                        "dateUpdated": null,
                        "remark": null
                    }
                ]
            },
            {
                "id": 3,
                "commodityCombinationId": 1,
                "calName": "保额",
                "calCode": "insuredAmount",
                "enuCode": "500000",
                "enuContent": "50万",
                "commodityFlag": "0",
                "commodityId": null,
                "calOrder": 2,
                "isCal": "1",
                "isDefalut": null,
                "showType": "listArea",
                "isRequired": null,
                "calOptions": [
                    {
                        "id": 3,
                        "commodityCombinationId": 1,
                        "calName": "保额",
                        "calCode": "insuredAmount",
                        "enuCode": "500000",
                        "enuContent": "50万",
                        "commodityFlag": "0",
                        "commodityId": null,
                        "calOrder": 2,
                        "isCal": "1",
                        "isDefalut": "1",
                        "showType": "listArea",
                        "isRequired": "1",
                        "createdBy": null,
                        "dateCreated": null,
                        "updatedBy": null,
                        "dateUpdated": null,
                        "remark": null
                    },
                    {
                        "id": 4,
                        "commodityCombinationId": 1,
                        "calName": "保额",
                        "calCode": "insuredAmount",
                        "enuCode": "1000000",
                        "enuContent": "100万",
                        "commodityFlag": "0",
                        "commodityId": null,
                        "calOrder": 2,
                        "isCal": "1",
                        "isDefalut": "0",
                        "showType": "listArea",
                        "isRequired": "1",
                        "createdBy": null,
                        "dateCreated": null,
                        "updatedBy": null,
                        "dateUpdated": null,
                        "remark": null
                    }
                ]
            },
            {
                "id": 5,
                "commodityCombinationId": 1,
                "calName": "保障期限",
                "calCode": "guaranteeTerm",
                "enuCode": "1",
                "enuContent": "一年",
                "commodityFlag": "0",
                "commodityId": null,
                "calOrder": 3,
                "isCal": "0",
                "isDefalut": null,
                "showType": "label",
                "isRequired": null,
                "calOptions": [
                    {
                        "id": 5,
                        "commodityCombinationId": 1,
                        "calName": "保障期限",
                        "calCode": "guaranteeTerm",
                        "enuCode": "1",
                        "enuContent": "一年",
                        "commodityFlag": "0",
                        "commodityId": null,
                        "calOrder": 3,
                        "isCal": "0",
                        "isDefalut": "1",
                        "showType": "label",
                        "isRequired": "1",
                        "createdBy": null,
                        "dateCreated": null,
                        "updatedBy": null,
                        "dateUpdated": null,
                        "remark": null
                    }
                ]
            },
            {
                "id": 6,
                "commodityCombinationId": 1,
                "calName": "年龄",
                "calCode": "insuredAge",
                "enuCode": "01",
                "enuContent": "18",
                "commodityFlag": "0",
                "commodityId": null,
                "calOrder": 4,
                "isCal": "1",
                "isDefalut": null,
                "showType": "date",
                "isRequired": null,
                "calOptions": [
                    {
                        "id": 6,
                        "commodityCombinationId": 1,
                        "calName": "年龄",
                        "calCode": "insuredAge",
                        "enuCode": "01",
                        "enuContent": "18",
                        "commodityFlag": "0",
                        "commodityId": null,
                        "calOrder": 4,
                        "isCal": "1",
                        "isDefalut": "1",
                        "showType": "date",
                        "isRequired": "1",
                        "createdBy": null,
                        "dateCreated": null,
                        "updatedBy": null,
                        "dateUpdated": null,
                        "remark": null
                    },
                    {
                        "id": 7,
                        "commodityCombinationId": 1,
                        "calName": "年龄",
                        "calCode": "insuredAge",
                        "enuCode": "01",
                        "enuContent": "59",
                        "commodityFlag": "0",
                        "commodityId": null,
                        "calOrder": 4,
                        "isCal": "1",
                        "isDefalut": "0",
                        "showType": "date",
                        "isRequired": "1",
                        "createdBy": null,
                        "dateCreated": null,
                        "updatedBy": null,
                        "dateUpdated": null,
                        "remark": null
                    }
                ]
            }
        ]
    }
}